### ISSUE TITLE
ipdb 0.8.1 is not published yet

### ISSUE THREAD

**Issue by NorthIsUp** [narfdotpl/debug#6]
oldest version as of right now is 0.8 https://pypi.python.org/pypi/ipdb

**Comment by narfdotpl** [comment]
Oops, thanks!

**Comment by narfdotpl** [comment]
Fixed and released to PyPI. :sparkles:

**Comment by gotcha** [comment]
Published now https://pypi.python.org/pypi/ipdb/0.8.1

**Comment by narfdotpl** [comment]
Thanks, @gotcha. Since the requirement is specified as `>= 0.8`, there's nothing to change on `debug` side, I think.
